baseurl: "https://nimodai.xyz/"
languageCode: "en-us"
title: "nimodai-blog"
theme: "hugo-tania"

params:
  titleEmoji: 'ğŸ˜'
  socialOptions:
    github:
    twitter: 

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"
    - name: äº¬ICPå¤‡16001475å·-2
      url: "http://beian.miit.gov.cn"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true